version: '3.3'

services:
  frontend:
    container_name: drugstone_stable_frontend
    image: gitlab.rrz.uni-hamburg.de:4567/cosy-bio/drugst.one/website:prod
    restart: always
    ports:
      - 8181:80
    networks:
      - drugstone-stable
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  backend:
    image: gitlab.rrz.uni-hamburg.de:4567/cosy-bio/drugst.one/backend:prod
    container_name: drugstone_stable_backend
    command: 
      - "sh"
      - "scripts/docker-entrypoint.sh"
    env_file:
      - 'docker-django.stable.env'
    restart: always
    volumes:
      - drugstone_stable_db_schema_volume:/usr/src/drugstone/drugstone/migrations
      - drugstone_stable_data_volume:/usr/src/drugstone/data
    ports:
      - 8182:8000
    networks:
      - drugstone-stable
    depends_on:
      - db
      - redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: postgres:14
    container_name: drugstone_stable_postgres
    restart: always
    hostname: drugstone_stable_postgres
#    ports:
#      - 5432:5432
    networks:
      - drugstone-stable
    volumes:
      - drugstone_stable_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=drugstone
      - POSTGRES_USER=drugstone
      - POSTGRES_PASSWORD=t6278yczAH7rPKVMxaDD
    command: 
      - "postgres"
      - "-c" 
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"
  redis:
    image: redis
    container_name: drugstone_stable_redis
    restart: always
    command: ["redis-server"]
    networks:
      - drugstone-stable
#    ports:
#      - 6379:6379
  celery:
    image: gitlab.rrz.uni-hamburg.de:4567/cosy-bio/drugst.one/backend:prod
    command:
      - "sh"
      - "scripts/start_celery_worker.sh"
    restart: always
    container_name: drugstone_stable_celery
    hostname: drugstone_stable_celery
    volumes:
      - drugstone_data_volume:/usr/src/drugstone/data
    env_file:
      - './docker-django.stable.env'
    depends_on:
      - redis
      - db
    networks:
      - drugstone-stable
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  celery-beat:
    image: gitlab.rrz.uni-hamburg.de:4567/cosy-bio/drugst.one/backend:prod
    command:
      - "sh"
      - "scripts/start_celery_beat.sh"
    container_name: drugstone_stable_celery_beat
    hostname: drugstone_stable_celery_beat
    restart: always
    env_file:
      - './docker-django.stable.env'
    depends_on:
      - redis
      - db
    networks:
      - drugstone-stable
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
#  cdn:
#    build: cdn
#    image: drugstone_cdn
#    container_name: drugstone_cdn
#    restart: always
#    volumes:
#      - drugstone_cdn_volume:/app/files
#    ports:
#      - 8033:80

networks:
  drugstone-stable:

volumes:
  drugstone_stable_db_volume:
    external: true
  drugstone_stable_db_schema_volume:
    external: true
  drugstone_stable_data_volume:
    external: true
  drugstone_stable_cdn_volume:
    external: true