version: '3.3'

services:
  app:
    image: drugstone_backend
    container_name: drugstone_backend
    build: .
    env_file:
      - 'docker-django.env'
    restart: always
    volumes:
      - drugstone_usr_volume:/usr/src/drugstone/data_drugstone/
    ports:
      - 8001:8000
    networks:
      - drugstone_net
    depends_on:
      - db
      - redis
  db:
    image: postgres
    container_name: drugstone_postgres
    restart: always
    hostname: drugstone_postgres
    ports:
      - 5432:5432
    networks:
      - drugstone_net
    volumes:
      - drugstone_postgres_volume:/var/lib/postgresql/data_drugstone/
    environment:
      - POSTGRES_DB=drugstone
      - POSTGRES_USER=drugstone
      - POSTGRES_PASSWORD=t6278yczAH7rPKVMxaDD
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"
  redis:
    image: redis
    container_name: drugstone_redis
    hostname: drugstone_redis
    restart: always
    command: ["redis-server"]
    networks:
      - drugstone_net
  celery:
    restart: always
    build: .
    container_name: drugstone_celery
    hostname: drugstone_celery
    command: celery -A core worker -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - db
    networks:
      - drugstone_net
  celery-beat:
    build: .
    container_name: drugstone_celery_beat
    hostname: drugstone_celery_beat
    command: celery -A core beat -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - redis
      - db
    networks:
      - drugstone_net

networks:
  drugstone_net:

volumes:
  drugstone_postgres_volume:
  drugstone_usr_volume: